---

server:
  port: 8080
spring:
  thymeleaf:
    cache: false       # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/webapp/   # Trailing / mandatory            # Template location for this application only
    suffix: .jsp
  application:
    name: frontend
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: offer
