---

server:
  port: 8761
spring:
  application:
    name: main-server
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      host: localhost
      port: 27017
      database: main

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
